### ISSUE TITLE
analyzeCallback 没有及时释放导致了内存泄漏

### ISSUE THREAD

**Issue by blisssayyid** [Dkaishu/ZXingLib#1]
annoyanonymous implementation of com.dkaishu.zxinglib.activity.CodeUtils$AnalyzeCallback

**Comment by Dkaishu** [comment]
呀 啥情况 待我有时间瞅瞅

**Comment by blisssayyid** [comment]
通过在activity里面的如下解决：

```
analyzeCallback = null;
captureFragment.setAnalyzeCallback(null);
```

**Comment by Dkaishu** [comment]
没有看出来会内存泄漏啊，anctivity 持有 analyzeCallback ，finsh()时就销毁释放了
